### ISSUE TITLE
geolocation

### ISSUE THREAD

**Issue by cbanwell** [Svrf/svrf-api#32]
# Support request

Hi,

Wondered if you have any plans to allow users to post content based on geolocation, ie. user takes a 360degree photo say in the centre of London, and posts it as a geo tagged object, would we then be able to query the database with objects near a certain location.

**Comment by brentchow** [comment]
Hey @cbanwell, thanks for the request. You’re not the first person to ask for this.

Can you help us understand your usecase and how much of a priority a feature like this is for you?

Thanks in advance!

**Comment by cbanwell** [comment]
Hiya,

The use case is a 3d travel app whereby we'd like to show user content based on the location it was posted, we have a beta app on the app store if you'd like to take a look.

https://play.google.com/store/apps/details?id=com.gofindpublic.xr

Maybe it's something we can work on together somehow.

**Comment by brentchow** [comment]
Currently, we aren't planning on adding geolocation to the API; however, that could change pending the number of requests.

With that said, you can query for places such as `London,` or even more specific places like `Notting Hill`, `South Kensington`, or even landmarks like `Big Ben`, `Buckingham Palace`, etc.

**Comment by cbanwell** [comment]
Ahh cool which field in the search api would I use for it?

**Comment by brentchow** [comment]
You can use the [search endpoint](https://developers.svrf.com/docs/#operation/search) and include the location in the query (`q`).

For example, you could request `https://api.svrf.com/v1/vr/search?q=eiffel%20tower` and it would show results like https://www.svrf.com/search/eiffel%20tower

[![eiffel tower on svrf - embed](https://www.svrf.com/storage/svrf-previews/104407/images/thumbLargeWatermark.jpg)](https://www.svrf.com/embed/vr/104407)

**Comment by brentchow** [comment]
We're actively investigating and prioritizing this ticket.
