### ISSUE TITLE
Hi there,

### ISSUE THREAD

**Issue by cbanwell** [Svrf/svrf-api#33]
# Support request

What are the steps to get the code to work in the Unity environment?

I've imported both client packages (client and test), but get 400+ errors most relating to NUnit undefined, and RestSharp.

ex.
Assets\svrf-csharp-client-master (1)\SVRF.Client.Test\Api\AuthenticateApiTests.cs(18,7): error CS0246: The type or namespace name 'NUnit' could not be found (are you missing a using directive or an assembly reference?)

Any help appreciated.

**Comment by RomanFrom710** [comment]
Hi @cbanwell, did you install it from [NuGet](https://www.nuget.org/packages/SVRF.Client/) package manager?

The SVRF client library has some dependencies, they're installed automatically when using NuGet. If you've copied the client manually, you have to add these dependencies manually as well. But the recommended way is install it using NuGet.

**Comment by cbanwell** [comment]
Yeah I did it manually

**Comment by brentchow** [comment]
Hi @cbanwell, we wanted to follow up and let you know we've released a Unity plugin! This should make installation much much easier! 😄

You can find it in the Svrf-Unity repo's [releases](https://github.com/Svrf/svrf-unity/releases). You can checkout the new [documentation and guides](https://docs.svrf.com/docs/unity) to help you get started.
