### ISSUE TITLE
Create Unity Plugin Documentation

### ISSUE THREAD

**Issue by SreekanthKadari** [Svrf/svrf-api#37]
Create documentation and a quick start guide on how to use the Unity Plugin.

**Comment by SreekanthKadari** [comment]
I would like to use your apk for my Background subtraction I have found you in your web site. I have installed your SVRF.client. But how can use your api in unity??

Thanks and Regards
K VenkataSrikanth

**Comment by RomanFrom710** [comment]
Hi @SreekanthKadari ,

Thank you for your interest in our API!

Our API (and therefore the C# library) provides only links to 3D model files, so you have to download them and insert into Unity scene in your code manually. Probably you'll have to use external loader to load our models (I recommend [this](https://github.com/KhronosGroup/UnityGLTF) one for GLTF models).

However, now we're working on the Unity plugin that would simplify loading and using 3D models (especially face filters) from our API.

Regards,
Roman

**Comment by brentchow** [comment]
@SreekanthKadari to add to @RomanFrom710's comment, with our upcoming Unity plugin you'll be able to load content into your scene at runtime.

Currently, you'll only need to use the loader he mentioned if you need to load 3D models.

We'll keep you informed on when the Unity plugin releases. Please let us know if you have any more questions.

**Comment by brentchow** [comment]
I've gone through and cleaned up the docs. You did a great job! I consolidated the Docs in to a `Unity / C#` section.

The only thing I think that is missing is in the C# reference we could include a Unity section with the Unity specific method `GetSvrfModelAsync`

**Comment by brentchow** [comment]
> The only thing I think that is missing is in the C# reference we could include a Unity section with the Unity specific method `GetSvrfModelAsync`

@RomanFrom710 I added these docs https://docs.svrf.com/reference/csharp-unity#csharp-getsvrfmodelasync

**Comment by brentchow** [comment]
Hi @SreekanthKadari, we wanted to follow up and let you know we've released a Unity plugin! You can find it in the Svrf-Unity repo's [releases](https://github.com/Svrf/svrf-unity/releases). We also added the [guides](https://docs.svrf.com/docs/unity) you requested to make it easy to get started! 😃
