### ISSUE TITLE
Face Filter

### ISSUE THREAD

**Issue by moh1122** [Svrf/svrf-api#43]
Hello
Thank you for this great API its hilarious, well id like to ask more about the face filters and the glasses when they are on the face a grey mask is with them, is there a way that the glasses will be on the face without the mask?

**Comment by sopify** [comment]
Hi!

Thanks for reaching out! Which client library are you using the API on?

Thanks in advance,

Sophia

@sophiaedm ( http://twitter.com/sophiaedm )
@svrf ( http://twitter.com/svrf ) / svrf.com ( http://svrf.com )

**Comment by moh1122** [comment]
Hello 
Well im using ios sdk. I just build the example project that was provided. Pod'SvrfSDK' is installed.

**Comment by AndreiEvstratenko** [comment]
Hey, @moh1122!

We will update our example, but, currently, you can use `generateFaceFilterNode` function instead of `generateNode` on line 40 in `RemoteFaceFilter.swift` file and you will get what you want

Thanks in advance,

Andrei

**Comment by moh1122** [comment]
Thank you @AndreiEvstratenko its working now :)

**Comment by AndreiEvstratenko** [comment]
You're welcome! @moh1122
