### ISSUE TITLE
Add all filters

### ISSUE THREAD

**Issue by moh1122** [Svrf/svrf-api#44]
Hello
Well id like to suggest a feature request i was thinking about is to ass a button to show all the face filters from svrf.com this will help the users see all the filters and they can click the one they like and if they don't want to see them all then they can search.
BTW is there any search criteria that an show all the filters like * ?

**Comment by brentchow** [comment]
Hi @moh1122, we suggest using the [Trending Endpoint](https://docs.svrf.com/reference/media#gettrending) and filtering for face filters. This should give your users a good starting point before searching for face filters.

For example:

```sh
curl --request GET \
  --url 'https://api.svrf.com/v1/vr/trending?isFaceFilter=true' \
  --header 'accept: application/json' \
  --header 'x-app-token: xxxxxxxxxxxxxx'
```

**Comment by moh1122** [comment]
Hello @brentchow im using the ios sdk.
How can I add it to it ?

**Comment by brentchow** [comment]
You can use the [`getTrending`](https://docs.svrf.com/reference/ios-endpoints#ios-gettrending) function in the SDK. Check out this [section](https://docs.svrf.com/docs/ios-sdk-api-requests#section-get-trending) of the quick start guide; I think it should be helpful.

```swift
let options = SvrfOptions(
  type: nil,
  stereoscopicType: nil,
  category: nil,
  size: nil,
  minimumWidth: nil,
  isFaceFilter: true,
  hasBlendShapes: nil,
  requiresBlendShapes: nil,
  pageNum: nil
)

SvrfSDK.getTrending(options: options, onSuccess: { (mediaArray, nextPageNum) in
  if !mediaArray.isEmpty {
    // Do what you want with the [SvrfMedia]?
  } else {
    // The Svrf API responeded with no SvrfMedia
}) { error in
  // Optional error handling
  print("\(error.svrfDescription). \(String(describing: error.localizedDescription))")
}
```

**Comment by moh1122** [comment]
Thank you so much that's soo helpful, I was able to get the most trending, but what I want exactly is to get all the face filters at once I was able to get most of them when I added an int to the size like size: 999, instead of nil.
Is there a way to call all the filters at once not only the trending ones.

**Comment by brentchow** [comment]
I'm sorry, but we currently do not offer a way to get all face filters with one API endpoint request.

We will make a note of your request and take it into consideration.

Please let us know if there are any other questions we can help you with.
