### ISSUE TITLE
iOS 13 Beta - `ARWorldTrackingConfiguration` Support

### ISSUE THREAD

**Issue by moh1122** [Svrf/svrf-api#45]
Hello
Im using iOS API Ive realized that it only supports ARFaceTrackingConfiguration. I added a rotate camera button and added 

            // Create a session configuration
            let configurationback = ARWorldTrackingConfiguration()

            // Run the view's session
            sceneView.session.run(configurationback)
          
            sceneView.automaticallyUpdatesLighting = true
            
            // Keep the screen on
            UIApplication.shared.isIdleTimerDisabled = true
     
when I press it inside the app and place it on a human face the filters dont appear at all and when I rotate to ARFaceTrackingConfiguration everything works normal.
Can you help me fix that to make it work with ARFaceTrackingConfiguration.
Thank you

**Comment by brentchow** [comment]
ARKit 2 face tracking currently requires [`ARFaceTrackingConfiguration`](https://developer.apple.com/documentation/arkit/arfacetrackingconfiguration) which is only supported on the TrueDepth front facing camera.

At WWDC 2019, Apple announced that ARKit 3 will support back camera face tracking. We have not tested the iOS 13 Beta.

**Comment by moh1122** [comment]
Hello @brentchow yep i know that and im testing it in ios13 thats why im asking ?

**Comment by AndreiEvstratenko** [comment]
Hey, @moh1122

I'll install iOS 13 and try to help you

**Comment by moh1122** [comment]
they you @AndreiEvstratenko for your quick support

**Comment by AndreiEvstratenko** [comment]
Hey, @moh1122!

We attempted to test ARKit on the iOS 13 Beta. It appears to be very buggy. At this time we can't guarantee support for an operating system in beta. We will continue to look into supporting iOS 13 before the in the late summer/early fall launch of the new OS.

**Comment by moh1122** [comment]
I realized that also and now more bugs in ios 13 beta 3

**Comment by brentchow** [comment]
Hi @moh1122, according to the [documentation](https://developer.apple.com/documentation/arkit/arworldtrackingconfiguration/3223422-userfacetrackingenabled), ARKit 3 does not support face tracking on the back facing camera. Face tracking in world tracking mode actually uses the front facing camera so "you can share avatar expressions with multiple users in a multiplayer game, or enable the player to control a virtual object in the physical environment using facial expressions."
